### ISSUE TITLE
Box-sizing?

### ISSUE THREAD

**Issue by ivan-kleshnin** [kognise/water.css#237]
Was surprised to not find the following (or something similar) in the code:

```
 html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```

I think it's included it every reset library I'm aware of.

**Comment by Brettasearle** [comment]
I can add this!

**Comment by jonaskuske** [comment]
Yeah, it's not included because this isn't a general-purpose *reset library*, it's "just" a set of default styles you can apply to your vanilla document to make it look nice by default, so it only includes style rules that are necessary to achieve that goal. Other popular CSS libraries with a similar goal would be [sakira](https://github.com/oxalorg/sakura), [mvp.css](https://github.com/andybrewer/mvp) or [new.css](https://github.com/xz/new.css) which also don't include a generel `box-sizing` override FWIW.

So much for the explanation – maybe @kognise or @kylejrp are still fine with adding the respective rule, just pointing out that this isn't exactly in scope as of now.

**Comment by kylejrp** [comment]
My gut feeling is not to include because this feels like a breaking change for anything built on top of water.css, but I could be convinced otherwise! I know I had a similar thought early on in the project to include this but I never pushed for it

**Comment by adeleke5140** [comment]
what issue is this about? I'd be glad to get clarifications so that I could work on it

**Comment by itsdeekay** [comment]
> what issue is this about? I'd be glad to get clarifications so that I could work on it
Hi @adeleke5140 
This issue is regarding use of famous box-model as default model to style the html elements. @kylejrp  is looking for some approach or genuine reason to add this as default box-sizing style.

**Comment by kognise** [comment]
Added as a breaking change for 3.0.0.
