### ISSUE TITLE
<q> tag margin

### ISSUE THREAD

**Issue by LouisDeconinck** [kognise/water.css#261]
It seems like not enough margin is added to the q-tag, because I get the following results when putting some inline quotes next to each other:
![qtag](https://user-images.githubusercontent.com/27673665/135101227-afb0294f-cdd5-48a0-8b84-c44b97f362bc.png)

**Comment by Matheus-Melo** [comment]
I found a solution for this, the margin wouldn't work since the display is inline, so instead I added line height to the <q> tag. It won't overlap the adjacent lines anymore, but every line whithin the tag will have a bigger spacing, making it look weird if the inline quote takes more lines, but in that case an actual block quote would be the best solution anyway.

**Comment by kognise** [comment]
Ended up just fixing this by *removing* Water.css quote styles, leaving the default browser double quotes which are more than enough.
