### ISSUE TITLE
Support for text-level semantics

### ISSUE THREAD

**Issue by rahuldottech** [kognise/water.css#32]
1. `<kbd` and `<code>` should not have the same visual styles
2. Support for `<samp>`
3. Support for `<mark>`
4. Support for `<var>`
5. Support for `<time>`
6. Support for `<small>`
7. Support for `<data>` (?? -- rarely used -- not in w3c spec, but in WHATWG)
8. Support for `<q>`
9. Support for `<cite>`

I'm not sure if the following require custom styling: `<abbr>`, `<dfn>`, `<ruby>`, `<rp>`, `<rt>`, `<bdi>`

**Comment by kylejrp** [comment]
We'd love to have contributors on this issue! I think the work can be broken into the six points in @rahuldottech's comment above. Feel free to claim any or all of these points!

To contribute, we'd be looking for you to create or update the relevant `.scss` file in `/src/parts/`. You'll want to reuse any variables from `src/dark.scss` or `src/light.scss` if they make sense, or create and reference new variables if necessary.

Feel free to ask for any help or if you have any questions about how to contribute!

**Comment by asoback** [comment]
I'd love to contribute.

Light theme:
![image](https://user-images.githubusercontent.com/31739297/58349214-4b61c100-7e28-11e9-83e7-9cf9c642c302.png)

Dark Theme:
![image](https://user-images.githubusercontent.com/31739297/58349253-692f2600-7e28-11e9-929b-980d1b364a16.png)

I changed the color of `<var>` to differentiate it, I'm not sure there needs to be any change with `<cite>` `<q>` or `<blockquote>`

I changed the color of `<mark>` background for dark mode to be easier on the eyes.

Let me know what you think, I'm happy to take any suggestions and make changes. I've only messed around with dark.css and light.css, but if you think this looks good, I can submit a PR with changes to the .scss files.

**Comment by kylejrp** [comment]
Great work @asoback! 

Can you show some examples of what the `<kbd>` element looks like with some example keys? Something like `<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd>`.

For `<var>` and `<time>`, is the font size changing? It's hard to tell in your screenshot. I think that the font should stay the same height so that code examples have uniform height across a line. It would be okay to change the font weight a little, but maybe not the height.

Should `<q>` and `<blockquote>` share the same style?

Anyways, I think this looks great. I'd love to see a pull request for this!

**Comment by kylejrp** [comment]
@asoback, should #93 close this issue? Or were there still outstanding elements in this issue that your pull request didn't cover?
