### ISSUE TITLE
How about adding a config file, such as linter?

### ISSUE THREAD

**Issue by kimulaco** [kognise/water.css#73]
I saw this PR(https://github.com/kognise/water.css/pull/23).
I think it is a good idea to add Linter.
Currently, gulpfile.js does not standardize the presence of semicolons and the style of indent.

However, it is inefficient to create all linter settings manually.
So I suggest creating a config based on [JavaScript Standard Style](https://standardjs.com/)([eslint-config-standard](https://github.com/standard/eslint-config-standard)).

In addition, I think that it is also effective to set up the next.

- [stylelint](https://stylelint.io/)
- [EditorConfig](https://editorconfig.org/)

If you have an opinion please!
If you are considering adding, I can give PR. (It will take a little while.)

**Comment by jonaskuske** [comment]
I thought about this too for a while, so thanks for starting that discussion!

My thought was to go with a combination of ESLint, Stylelint and [prettier](https://prettier.io/) (integrated through `eslint-plugin-prettier` and `stylelint-prettier` respectively) to catch mistakes (ESLint, Stylelint) and enforce common formatting guidelines (prettier).
We would integrate this though [`husky`](https://github.com/typicode/husky) and [`lint-staged`](https://github.com/okonet/lint-staged) with out Git setup. This way, whenever a Contributor commits something, all the files that are selected for the commit will be linted & fixed automatically, so we can be sure that everything in the repo will adhere to our code guidelines, but contributors don't have to configure linting and the respective Editor integrations themselves (if they don't want to). They can format code they write however they want, but once they check it in, it will be formatted to match our rules.

I like prettier because it's very opinionated (so you don't have to discuss style preferences) and because it can format pretty much anything: CSS, JS, Markdown, JSON...
But only if everyone here can live with prettier's formatting rules, of course.

**Comment by kylejrp** [comment]
I'm on board for this. I like the idea of an opinionated default configuration that we don't customize.

Having it work with editors and during commits is a great idea and we should make sure that's supported.

I'm curious what @kognise thinks. You can propose a pull request but I'll want @kognise to approve.
