### ISSUE TITLE
Fix switch theme button for IE11

### ISSUE THREAD

**Issue by kylejrp** [kognise/water.css#89]
I haven't nailed down the source of this problem, but the "Switch Theme" button on the demo page has been broken on IE11 for a while.

This change was **not** introduced by #85. However, #85 may have added more compatibility issues on top of it.

We could try tracing down the original source of the problem, or we could just update the build tools to automatically support IE11 and other browsers.

**Comment by kimulaco** [comment]
@kylejrp Thank you for making the issue!
Since I corresponded to #85 , I would like to correspond to this issue as well.

**Comment by kognise** [comment]
I'm on macOS right now - is there a way for me to test this? If not would someone with ie11 mind jumping on this issue?

**Comment by kylejrp** [comment]
If I recall correctly it has to due with IE11 not supporting the arrow function syntax.

You can manually convert arrow functions to the older syntax to fix it.

We should be looking to transpile the JavaScript on the demo page for IE11 compatibility similar to how our CSS build targets IE11 for CSS compatibility

I can test it this evening if nobody else can jump on it before then

**Comment by kylejrp** [comment]
This wouldn't be strictly required for a 2.0 launch now that I think about it - it's just a bug in the demo site. Feel free to remove it from the milestone if you agree.

**Comment by jonaskuske** [comment]
Yeah, we need to transpile `script.js` and load `URLSearchParams` and `Promise` polyfills if the browser doesn't support them natively. I can take care of that, along with a general refactor/cleanup :)

**Comment by jonaskuske** [comment]
This is fixed in 2.0 (#194) – `script.js` is transpiled now and I've made sure that we only use APIs that are available in IE, e.g. `child.parentElement.removeChild(child)` vs. just `child.remove()`. Also, a polyfill for the async clipboard API and Promise is loaded if necessary.

Only (minor) issue that remains is that our Lint rules (which require us to use ES6 arrow functions) apply to inline `<script>` in the HTML, but the code there is *not* transpiled, so we need to use standard functions there for IE compat and manually disable the ESLint errors. But I think that's okay, it only affects the Analytics snippet and not much more.
