### ISSUE TITLE
GitHub pages site doesn't redirect to the new site

### ISSUE THREAD

**Issue by MazeChaZer** [kognise/water.css#99]
When I visit <https://kognise.github.io/water.css/>, I get a 404 for the CSS file and no styles are applied.

**Comment by MazeChaZer** [comment]
I just saw that the demo page seems to have moved to netlyfly. Perhaps include a redirect on the old page?

**Comment by kylejrp** [comment]
I don't have experience with GitHub pages, but we'd take a pull request for configuring the redirect if possible.

**Comment by kimulaco** [comment]
@kylejrp @kognise 
I investigated how to redirect from Github Pages to Netlify, it seems to be mainly the following two.

- Use a jekyll plugin (`jekyll-redirect-from`)
    - 301 Redirection is possible, so you can redirect properly to the crawler.
    - It is necessary to use gem, and the file which isn't related to water.css increases.
- Use `meta[http-equiv="refresh"]` and `link[rel="canonical"]`
    - Because it redirects after 200 OK, it is not the best site migration.
    - `link[rel ="canonical"]` can tell you that the actual state of the site is Netlify.
    - This is possible with the minimum necessary implementation.

Either way, you should change the branch of Github Page.
And since local development becomes difficult, it is better not to include redirect code in the master branch.

If either is decided, I can create a pull request!

**Comment by kognise** [comment]
Fixed in b8142463a627abad4aca387b2531cbd3a6783a8e.
